workflows:
  android-workflow:
    name: Android Workflow
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      groups:
        - keystore
 #       - google_play
        - other
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.keystore
        PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
        GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: "dfdf"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up key properties
        script: |
          #!/usr/bin/env zsh
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
      - name: Set up local.properties
        script: |
          #!/usr/bin/env zsh
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get       
      - name: Build APK with Flutter  
        script: |
          cd . && flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log